### ISSUE TITLE
Not getting any data

### ISSUE THREAD

**Issue by MrEldin** [freshOS/Networking#33] opened 2021-04-18 00:07 UTC
HI I have a problem and I don't know how to solve it because I don't have any error but I am not getting any data from the API call, I have this class:

```swift
import Foundation
import Combine
import SwiftUI
import Networking

class TimeStore: ObservableObject {
    @Published var times = ModuleRoot(data: Time())
    @State var cancellables = Set<AnyCancellable>()
    
    init() {
        self.updateData()
    }
    
    func updateData() {
        let day = Day.formatDate(type: "d", date: Date())
        let month = Day.formatDate(type: "M", date: Date())
        
        let network = NetworkingClient(baseURL: "https://somapi.com/api")
        network.get("/times/month/\(month)/day/\(day)").sink(receiveCompletion: { completion in
            print("echo")
            switch completion {
                case .finished:
                    break
                case .failure(let error):
                    switch error {
                        case is DecodingError:
                            let decodingError = error as! DecodingError
                            // handle JSON decoding errors
                            print("Decoding: \(decodingError)")
                        case is NetworkingError:
                            let networkingError = error as! NetworkingError
                            // handle NetworkingError
                            print("Networking: \(networkingError.status)")
                            print("Networking code: \(networkingError.code)")
                        default:
                            // handle other error types
                            print("\(error.localizedDescription)")
                    }
            }
        }) { (response: ModuleRoot<Time>) in
            DispatchQueue.main.async {
                self.times = response
                print("echo")
                print(self.times)
            }
        }.store(in: &cancellables)
    }
}
```
When I call this class in any view, I am not getting any results, I am not getting any echo printed, and I'm not getting data updated:

```swift
import Combine
import SwiftUI
import Networking

struct MainView: View {
    @ObservedObject var globalProgress = Progress()
    @ObservedObject var timeStore = TimeStore()
    
    var body: some View {
        NavigationView {
            VStack {
                
            }
        }.onAppear() {
            globalProgress.mainProgress = false
        }
    }
    
    
}

struct MainView_Previews: PreviewProvider {
    static var previews: some View {
        MainView()
    }
}
```

Can you please tell me where I am wrong?

**Comment by workingDog** [comment] 2021-04-18 12:34
There is not enough code to reproduce your error, however I believe you should have: 

    @State var cancellables = Set<AnyCancellable>()
    
outside of your TimeStore class, to have a strong reference to cancellables in MainView.

That means bringing func updateData() also into MainView.

**Comment by MrEldin** [comment] 2021-04-19 01:54
Ou, yeah if I do it like you made an example here that works very well, but that is not how I want it to be, I wanted to have a Store class that will do call to the API, and that wasn't possible for me. I don't want to make API calls from my view so I created my own Network layer with URLSession and made a call from the Store class. Sorry I had to remove the package from the project, so sorry for that.

So maybe I should close this issue now?

**Comment by workingDog** [comment] 2021-04-19 02:23
In your original TimeStore code, what if you change 
       `@State var cancellables = Set<AnyCancellable>()`
to
      `var cancellables = Set<AnyCancellable>()`

do you still get the issue?

Leave this open for a while, maybe someone will find a good solution.

**Comment by MrEldin** [comment] 2021-04-19 22:13
Hi, 

Thank you for your help and answers. Please just try to create any class I called it Store, but you can call it whatever and then just try to call any open API with this package, nothing will happen, but you will never get into closure, don't know why.

**Comment by workingDog** [comment] 2021-04-20 05:38
Ok, here is a simple example that may work for you (note I have a strong reference at the App level):

```
import SwiftUI
import Combine
import Networking

@main
struct NetworkingTestApp: App {
    var github = GHProvider()

    var body: some Scene {
        WindowGroup {
            ContentView().environmentObject(github)
        }
    }
}

struct ContentView: View {
    @EnvironmentObject var github: GHProvider
    
    var body: some View {
        Text("test Networking").onAppear(perform: dotest).padding()
    }
    
    func dotest() {
        github.getRepo(owner: "freshOS", repo: "Networking") { response, error in
            print("---> in dotest response: \(response)")
        }
    }
}

class GHProvider: ObservableObject {
    public var client: NetworkingClient
    public var cancellables = Set<AnyCancellable>()
    public let mediaTypev3 = "application/vnd.github.v3+json"
    
    public init() {
        self.client = NetworkingClient(baseURL: "https://api.github.com/")
        client.headers["Content-Type"] = mediaTypev3
        client.headers["Accept"] = mediaTypev3
    }
    
    func getRepo(owner: String, repo: String, handler: @escaping (String?, String?) -> Void) {
        let urlAddon = "repos/" + owner + "/" + repo
        client.get(urlAddon).sink(receiveCompletion: { completion in
            switch completion {
            case .finished:
                break
            case .failure(let error):
                print("---> in GHProvider getRepo error: \(error.localizedDescription)")
                return handler(nil, error.localizedDescription)
            }
        }) { (data: Data) in
            print("---> in GHProvider getRepo data: \(data)")
            if let theString = String(data: data, encoding: .utf8) {
                print("---> in GHProvider getRepo theString: \(theString)")
            }
            handler("Networking success", nil)
        }.store(in: &cancellables)
    }
}

```

**Comment by lukacs-m** [comment] 2021-04-20 08:27
Hello MrEldin,

I see two little things that could be change and should improve the behaviour of your store object.

As @workingDog said you don't need `@State` in front of your `var cancellables = Set<AnyCancellable>`.

But the most important part is that you should declare your store class with `@StateObject` in your view.

What is happening in your case is that anytime `MainView` detects a change in `TimeStore` it rebuild itself reinstantiating
`TimeStore `ans though killing your previous call.

The `@StateObject` keep a reference on the object keeping your previous call and answer alive.

Here is a little bit more explanation. [https://www.hackingwithswift.com/quick-start/swiftui/whats-the-difference-between-observedobject-state-and-environmentobject](ObservedObject vs StateObject).

Hope it helps

**Comment by workingDog** [comment] 2021-04-20 12:28
yes definitely, @StateObject works in my test. 

```
struct ContentView: View {
    
    @StateObject var github = GHProvider()
    
    var body: some View {
        Text("test Networking").onAppear(perform: dotest).padding()
    }
    
    func dotest() {
        github.getRepo(owner: "freshOS", repo: "Networking") { response, error in
            print("---> in dotest response: \(response)")
        }
    }
}
```

**Comment by s4cha** [comment] 2021-09-17 09:52
@workingDog @lukacs-m Thanks a ton for chiming in on this 👍  Indeed it looks like a SwiftUI issue rather than a Networking one. `@State` is not needed (and `cancellables` can be private). Using the viewModel as a `@StateObject` should resolve the lifecycle issue. closing this :)

**Closed by s4cha** 2021-09-17 09:52 UTC
